### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by binaryben** [tusaeff/vscode-iterm2-theme-sync#14]
It's driving me crazy. I've removed the extension because it was messing with my hotkeys.

Unfortunately it's still loading the synced profile in iTerm, even after I remove the profile and restart.

**Comment by satwanjyu** [comment]
`$ rm ~/.config/iterm2/AppSupport/DynamicProfiles/vscode-synced.json`

**Comment by binaryben** [comment]
Seems to have done it. Thanks @satwanjyu!
