### ISSUE TITLE
Extension doesn't play nice with non-macOS environments

### ISSUE THREAD

**Issue by jaminthorns** [tusaeff/vscode-iterm2-theme-sync#2]
I installed this extension on my MacBook with iTerm, and it worked great! Thing is, I sync my settings between multiple machines, and once I got my Windows machine up-to-date, it installed the extension there as well. Every time I started VS Code up after that, the extension sent me an error notification that it couldn't find the file location for the iTerm dynamic theme (because of course there is no iTerm on my Windows machine). 

For an extension that will only play well with one OS, there should be some OS-detection logic. The user might even have a macOS machine with iTerm and one without, so ideally it should play well with that as well. This could probably be done with some simple detection of whether the folder for iTerm dynamic profiles exists. If it doesn't, assume the user doesn't have iTerm and gracefully shut the extension down. If you must display some message, maybe show a warning notification with the option to never show it again through a setting (though I'm not a fan of having to pollute my settings with flags for disabling messages).

Thanks for your hard work on this extension!

**Comment by hanskokx** [comment]
Adding to this, I use (and contribute to) [Fluent Terminal](https://github.com/felixse/FluentTerminal), and I'd love to sync my theme from VSCode to FT.  Fluent Terminal uses [standard iTerm colors](https://github.com/felixse/FluentTerminal/blob/master/FluentTerminal.Models/TerminalColors.cs).
